# Scheduler that runs every 30 mins
#
name: Data maintenance

on:
  schedule:
    - cron:  '*/30 * * * *'
      # cron:  '*/30 * * * *'
      # cron thqt runs every dqy at 1pm
        # cron:  '0 13 * * *'



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11.3
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.3

    - name: Print environment variables
      run: echo "Home directory is $HOME"


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install packages
      run: |
        pip install git+https://${{ secrets.REPO }}:x-oauth-basic@github.com/scollorec/Utils.git
        pip install git+https://${{ secrets.REPO_STOCKDATA }}:x-oauth-basic@github.com/scollorec/Stockdata.git
        

    - name: Run Python function
      run: python -c 'from test import data_maintenance; data_maintenance()'
      env:
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          SQLITE_FILE_ID: ${{ secrets.SQLITE_FILE_ID }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
          DATABASE_USER: ${{ secrets.DATABASE_USER }}
          DATABASE_PWD: ${{ secrets.DATABASE_PWD }}