name: Install packages from private repo

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 'env'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install packages
      run: |
        pip install git+https://${{ secrets.REPO }}:x-oauth-basic@github.com/scollorec/Utils.git

    - name: Run Python script
      run: python script.py
      env:
        SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        SQLITE_FILE_ID: ${{ secrets.SQLITE_FILE_ID }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
        DATABASE_USER: ${{ secrets.DATABASE_USER }}
        DATABASE_PWD: ${{ secrets.DATABASE_PWD }}



